name: Convert File to HDF

on:
  push:
    branches: [ master ]
    
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Convert file to HDF
        uses: mitre/heimdall_tools_action@v1.0
        with:
          file: 'sarif_input.sarif'
          converter: 'sarif'
